version: '3.3'

services:
  db:
    container_name: postgres10
    image: postgres:10
    volumes:
      - pgdb10:/var/lib/postgres-service/data
    environment:
      - POSTGRES_DB=apiservice
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "5432:5432"

volumes:
  pgdb10: